import './js/mobile-menu';
import './js/scroll-up';
import './js/footer-modal-team';
import './js/modal-film';
import './js/theme-switcher';
import './js/catalog-slider';
import './js/hero';
import './js/hero-modal-watch-trailer';
import './js/hero-slider';
import './js/loader';
// import './js/weekly-trends';
import './js/upcoming-mounth';
import './js/genres';
